# Generated by Django 3.2.20 on 2023-08-29 20:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Rock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('extra_info', models.TextField(blank=True)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('material', models.CharField(blank=True, max_length=255)),
                ('size', models.CharField(blank=True, max_length=50)),
                ('era', models.CharField(blank=True, max_length=255)),
                ('tools_used', models.TextField(blank=True)),
                ('date_found', models.DateTimeField(blank=True)),
                ('prepped_self', models.BooleanField(default=False)),
                ('image', models.ImageField(blank=True, default='../default_post_i7zqny', upload_to='images/')),
                ('finished_image', models.ImageField(blank=True, default='../default_post_i7zqny', upload_to='images/')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-title'],
            },
        ),
    ]
