# Generated by Django 3.2.20 on 2023-08-31 20:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Rock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('info', models.TextField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('material', models.CharField(blank=True, max_length=255, null=True)),
                ('size', models.CharField(blank=True, max_length=50, null=True)),
                ('era', models.CharField(blank=True, max_length=255, null=True)),
                ('tools', models.TextField(blank=True, null=True)),
                ('found', models.DateTimeField(blank=True, null=True)),
                ('prepped', models.BooleanField(default=False)),
                ('image', models.ImageField(blank=True, default='../default_post_i7zqny', upload_to='images/')),
                ('finished_image', models.ImageField(blank=True, default='../default_post_i7zqny', upload_to='images/')),
                ('image_filter', models.CharField(choices=[('ammonite', 'ammonite'), ('rock', 'rock'), ('fossil', 'fossil'), ('unknown_rock', 'unknown_rock'), ('unknown_fossil', 'unknown_fossil')], default='fossil', max_length=32)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-title'],
            },
        ),
    ]
