# Generated by Django 3.2.20 on 2023-08-29 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rocks', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rock',
            old_name='date_found',
            new_name='found',
        ),
        migrations.RenameField(
            model_name='rock',
            old_name='extra_info',
            new_name='info',
        ),
        migrations.RenameField(
            model_name='rock',
            old_name='prepped_self',
            new_name='prepped',
        ),
        migrations.RenameField(
            model_name='rock',
            old_name='tools_used',
            new_name='tools',
        ),
    ]
