# Generated by Django 3.2.20 on 2023-08-30 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rocks', '0002_auto_20230829_2056'),
    ]

    operations = [
        migrations.AddField(
            model_name='rock',
            name='image_filter',
            field=models.CharField(choices=[('ammonite', 'ammonite'), ('rock', 'rock'), ('fossil', 'fossil'), ('unknown_rock', 'unknown_rock'), ('unknown_fossil', 'unknown_fossil')], default='fossil', max_length=32),
        ),
    ]
